import { RunnableLambda, RunnableSequence } from "@langchain/core/runnables";

import { aiAnalysisService } from "@/lib/agent/ai-analysis-service";
import {
  buildFactualContextBlock,
  normalizeResearchData,
} from "@/lib/agent/data-normalizer";
import { validateResearchData } from "@/lib/agent/data-validator";
import { assembleInvestmentReport } from "@/lib/agent/report-assembler";
import { ApiError } from "@/lib/errors/api-error";
import { logger } from "@/lib/logger";
import { investmentReportSchema } from "@/lib/schemas/report.schema";
import { collectCompanyResearchDataOrThrow } from "@/lib/tools/research-data-collector";
import { fmpClient } from "@/lib/tools/fmp-client";
import type { CompanyResearchData } from "@/lib/types/data-layer";
import type {
  InvestmentReport,
  ResearchPipelineResult,
} from "@/lib/types/investment-report";

const SOURCE = "research-agent";

export interface ResearchAgentOptions {
  companyName: string;
  skipDataCollection?: boolean;
  preloadedData?: CompanyResearchData;
}

async function collectData(input: ResearchAgentOptions): Promise<CompanyResearchData> {
  if (input.preloadedData) {
    return input.preloadedData;
  }

  if (input.skipDataCollection) {
    throw new ApiError({
      code: "INVALID_INPUT",
      message: "preloadedData is required when skipDataCollection is true",
      source: SOURCE,
      retryable: false,
    });
  }

  return collectCompanyResearchDataOrThrow(input.companyName);
}

/**
 * LangChain-orchestrated investment research pipeline.
 *
 * Step 1: Validate collected data
 * Step 2: Normalize into structured factual context
 * Step 3: Pass verified facts to LLM (metrics never generated by model)
 * Step 4: Assemble typed investment report with verified metrics
 */
export class ResearchAgent {
  private pipeline = RunnableSequence.from([
    RunnableLambda.from(async (input: ResearchAgentOptions) => {
      logger.info(SOURCE, "Pipeline step: collect data", {
        company: input.companyName,
      });
      return collectData(input);
    }),
    RunnableLambda.from(async (data: CompanyResearchData) => {
      logger.info(SOURCE, "Pipeline step: validate data");
      const validated = validateResearchData(data);

      if (!validated.canProceed) {
        throw new ApiError({
          code: "INVALID_INPUT",
          message: "Insufficient data to generate an investment report",
          source: SOURCE,
          retryable: false,
          metadata: {
            issues: validated.issues,
            missingData: validated.missingData,
          },
        });
      }

      return validated;
    }),
    RunnableLambda.from(async (validated) => {
      logger.info(SOURCE, "Pipeline step: normalize data");
      const context = normalizeResearchData(validated.data, validated.missingData);

      logger.debug(SOURCE, "Factual context prepared", {
        ticker: context.ticker,
        metricCounts: {
          revenueGrowth: context.verifiedMetrics.revenueGrowth.length,
          profitability: context.verifiedMetrics.profitability.length,
          cashFlow: context.verifiedMetrics.cashFlow.length,
          debt: context.verifiedMetrics.debt.length,
          liquidity: context.verifiedMetrics.liquidity.length,
          valuation: context.verifiedMetrics.valuation.length,
        },
        newsFacts: context.newsFacts.length,
        contextLength: buildFactualContextBlock(context).length,
      });

      return { validated, context };
    }),
    RunnableLambda.from(async ({ validated, context }) => {
      logger.info(SOURCE, "Pipeline step: LLM analysis");
      const aiResult = await aiAnalysisService.generateNarrativeReport(context);
      return { validated, context, aiResult };
    }),
    RunnableLambda.from(async ({ validated, context, aiResult }) => {
      logger.info(SOURCE, "Pipeline step: assemble report");

      let stockPrices: Array<{ date: string; close: number }> = [];
      const priceResult = await fmpClient.getHistoricalStockPrices(context.ticker, 24);

      if (priceResult.success) {
        stockPrices = priceResult.data;
      } else {
        logger.warn(SOURCE, "Historical stock prices unavailable", {
          ticker: context.ticker,
        });
      }

      const report = assembleInvestmentReport(validated, context, aiResult, {
        stockPrices,
      });

      const schemaResult = investmentReportSchema.safeParse(report);

      if (!schemaResult.success) {
        throw new ApiError({
          code: "PARSE_ERROR",
          message: "Final report failed schema validation",
          source: SOURCE,
          retryable: false,
          metadata: {
            issues: schemaResult.error.issues.map((issue) => issue.message),
          },
        });
      }

      return schemaResult.data;
    }),
  ]);

  async generateReport(input: ResearchAgentOptions): Promise<ResearchPipelineResult> {
    const startedAt = Date.now();

    logger.info(SOURCE, "Starting research pipeline", {
      company: input.companyName,
    });

    try {
      const report = (await this.pipeline.invoke(input)) as InvestmentReport;

      logger.info(SOURCE, "Research pipeline completed", {
        company: input.companyName,
        ticker: report.meta.ticker,
        recommendation: report.finalRecommendation.verdict,
        confidence: report.confidenceScore.score,
        totalProcessingTimeMs: Date.now() - startedAt,
      });

      return {
        report,
        companyInput: input.companyName,
      };
    } catch (error) {
      logger.error(SOURCE, "Research pipeline failed", {
        company: input.companyName,
        error: error instanceof ApiError ? error.toJSON() : String(error),
        totalProcessingTimeMs: Date.now() - startedAt,
      });

      throw error;
    }
  }
}

export const researchAgent = new ResearchAgent();

export async function generateInvestmentReport(
  companyName: string,
): Promise<ResearchPipelineResult> {
  return researchAgent.generateReport({ companyName });
}
